version: 0.2

env:
  variables:
    ECR_REPOSITORY: 569313629397.dkr.ecr.ap-northeast-1.amazonaws.com/api-repository
    DOCKER_SECRET_VALUE: "arn:aws:secretsmanager:ap-northeast-1:569313629397:secret:prod/docker-login-wxUTwm"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - DOCKER_HUB_USERNAME = $(echo $DOCKER_SECRET_VALUE | jq -r '.DOCKER_HUB_USERNAME')
      - DOCKER_HUB_PASSWORD = $(echo $DOCKER_SECRET_VALUE | jq -r '.DOCKER_HUB_PASSWORD')
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin ${ECR_REPOSITORY}
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t container-test-app .
      - docker tag container-test-app:latest ${ECR_REPOSITORY}:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push ${ECR_REPOSITORY}:latest
      - echo Build completed on `date`
      - echo Creating imagedefinitions.json...
      - |
        echo '[
          {
            "name": "container-test-app",
            "imageUri": "'${ECR_REPOSITORY}':latest"
          }
        ]' > imagedefinitions.json
      - echo imagedefinitions.json created.

artifacts:
  files:
    - imagedefinitions.json
